CREATE DATABASE WINFORM_DM;

CREATE TABLE DESIGNER
(
NID INT PRIMARY KEY,
USERNAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PASS NVARCHAR(50) NOT NULL,
SALARY INT,
PICTURE IMAGE 
);
CREATE TABLE CLIENT(
NID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PASS NVARCHAR(50) NOT NULL,
PHONENO NVARCHAR(50) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
PICTURE IMAGE
);

SELECT * FROM DESIGNER ;
SELECT * FROM CLIENT;

CREATE TABLE ADMIN_A(
NID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PASS NVARCHAR(50) NOT NULL,
PHONENO NVARCHAR(50) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
PICTURE IMAGE
);

SELECT * FROM ADMIN_A ;
INSERT INTO ADMIN_A VALUES(012,'ALISON','alison76@gmail.com','12#5','01356472800','Gulsan','D:\Dream_Interior\image');

